<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .quotation-container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        .details {
            margin-bottom: 20px;
        }

        .details p {
            margin: 5px 0;
            font-size: 16px;
        }

        .quotation-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .quotation-table th, .quotation-table td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
        }

        .quotation-table th {
            background-color: #f8f8f8;
            color: #333;
        }

        .quotation-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .quotation-table tr:hover {
            background-color: #f1f1f1;
        }

    </style>
</head>
<body>

<div class="quotation-container">
    <h1>Quotation</h1>

    <div class="details">
        <p><strong>Date:</strong> {{ $date }}</p>
        <p><strong>Generated By:</strong> {{ $generatedBy }}</p>
    </div>

    <table class="quotation-table">
        <thead>
        <tr>
            <th>Sl</th>
            <th>Product Name</th>
            <th>Quantity</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $product['name'] }}</td>
                <td>{{ $product['quantity'] }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

</body>
</html>
